site_name: CSC1109 Data Speed and Scale
repo_url: https://github.com/amileo/CSC1109-Data-Speed-and-Scale
repo_name: amileo/CSC1109-Data-Speed-and-Scale
edit_uri: edit/main/docs/
docs_dir: docs
site_dir: site

theme:
  name: material
  logo: assets/logo.webp
  favicon: assets/favicon.svg
  font:
    text: "Inconsolata Nerd Font"
    code: "Inconsolata Nerd Font Mono"
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
  - search
  - autorefs
  - macros
  - section-index
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  - htmlproofer:
      validate_external_urls: true
  - spellcheck:
      known_words: dictionary.txt

nav:
  - Home: index.md
  - Lab1: lab1/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - callouts

extra_css:
  - assets/css/fonts.css
