version: "3.8"

x-hadoop-common-config:
  &hadoop-common-config
  image: ${HADOOP_RUNNER_IMAGE}:${HADOOP_RUNNER_VERSION}
  volumes:
    - .:/lab/
    - /opt/hadoop/:${HADOOP_HOME}
    - ./config/:${HADOOP_HOME}/etc/hadoop

services:
  namenode:
    <<: *hadoop-common-config
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED

  datanode:
    <<: *hadoop-common-config
    command: ["hdfs", "datanode"]
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    deploy:
      mode: replicated
      replicas: 4

  resourcemanager:
    <<: *hadoop-common-config
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED

  nodemanager:
    <<: *hadoop-common-config
    command: ["yarn", "nodemanager"]
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED

  client:
    image: ghcr.io/ca4022/csc1109-lab1-client
    hostname: client
    depends_on:
      - namenode
      - resourcemanager
    command: sleep infinity
    working_dir: /lab/
    volumes:
      - .:/lab/
      - /opt/hadoop/:${HADOOP_HOME}
      - ./config/:${HADOOP_HOME}/etc/hadoop
    environment:
      - SHELL=${SHELL}
      - EDITOR=${EDITOR}
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    stdin_open: true
    tty: true
