version: "3.8"

x-hadoop-common-config: &hadoop-common-config
  image: ${HADOOP_RUNNER_IMAGE}:${HADOOP_RUNNER_VERSION}
  volumes:
    - .:/lab/
    - /opt/hadoop/:${HADOOP_HOME}
    - ./config/:${HADOOP_HOME}/etc/hadoop/

x-spark-common-config: &spark-common-config
  image: ${SPARK_IMAGE}:${SPARK_VERSION}
  volumes:
    - /lab/:/lab/
    - ./config/:/var/config/hadoop/

services:
  namenode:
    <<: *hadoop-common-config
    hostname: namenode
    command: ["/opt/hadoop/bin/hdfs", "namenode"]
    ports:
      - 9870:9870
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
      - ENSURE_NAMENODE_DIR=/tmp/hadoop-root/dfs/name
    healthcheck:
      test: ["CMD", "curl", "-f", "http://namenode:9870"]
      interval: 10s
      timeout: 5s
      retries: 5

  datanode:
    <<: *hadoop-common-config
    command: ["/opt/hadoop/bin/hdfs", "datanode"]
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    deploy:
      mode: replicated
      replicas: 4
    depends_on:
      namenode:
        condition: service_healthy

  spark-master:
    <<: *spark-common-config
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    ports:
      - "8080:8080"

  spark-worker:
    <<: *spark-common-config
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    depends_on:
      - spark-master
    links:
      - spark-master
    deploy:
      mode: replicated
      replicas: 4

  client:
    image: ghcr.io/ca4022/csc1109-lab6-client
    environment:
      - SHELL=bash
      - HADOOP_HOME=${HADOOP_HOME}
      - HADOOP_USER_NAME=${HADOOP_USER_NAME}
      - HADOOP_OPTS=--add-opens=java.base/java.lang=ALL-UNNAMED
    ports:
      - 8888:8888
    depends_on:
      namenode:
        condition: service_healthy
      spark-master:
        condition: service_started
    links:
      - spark-master
    working_dir: /lab/
    volumes:
      - .:/lab/
      - ./config/:${HADOOP_HOME}/etc/hadoop/
    stdin_open: true
    tty: true
