name: Build and Push Base Container

on:
  push:
    branches:
      - main
      - workflows
    paths:
      - 'containers/base/**'
      - '.github/workflows/build-base.yml'
      - '.env'

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define runner, image name, and tags
        id: meta
        run: |
          TAG=$(just base get_tag)
          echo "CONTAINER_ENV=docker" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ env.BASE_CONTAINER_NAME }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/$TAG" >> $GITHUB_ENV

      - name: Build container image for testing
        run: |
          just base build

      - name: Test container image
        run: |
          echo "Running tests within the container..."
          docker run --privileged --rm ${{ env.IMAGE_TAG }} /test/test.sh
          echo "Container tests passed successfully!"

      - name: Tag and push container image to GHCR
        if: success()
        run: |
          echo "Tagging and pushing image to ghcr.io..."
          docker tag ${{ env.IMAGE_TAG }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_NAME }}:latest
          echo "Image pushed successfully."
