name: Reusable Container Build

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Load .env file
        id: dotenv
        uses: xom9ikk/dotenv@v2
        with:
          path: ./

      - name: Set container environment
        run: echo "CONTAINER_ENV=docker" >> $GITHUB_ENV

      - name: Enable Docker buildkit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Define image name and tag
        id: meta
        run: |
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_URL="ghcr.io/$REPO_OWNER_LOWER"
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
          VERSION_TAG=$(just get_tag ${{ inputs.path }})
          LATEST_TAG="$(just get_image_name ${{ inputs.path }}):latest"
          echo "VERSION_TAG_LOCAL=$VERSION_TAG" >> $GITHUB_ENV
          echo "VERSION_TAG_REMOTE=$REPO_URL/$VERSION_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG_REMOTE=$REPO_URL/$LATEST_TAG" >> $GITHUB_ENV

      - name: Check if remote tag exists
        id: check_tag
        continue-on-error: true
        run: |
          if docker manifest inspect ${{ env.VERSION_TAG_REMOTE }} > /dev/null; then
            echo "Tag ${{ env.VERSION_TAG_REMOTE }} already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag ${{ env.VERSION_TAG_REMOTE }} does not exist. Proceeding to build."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check_tag.outputs.exists == 'false'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: steps.check_tag.outputs.exists == 'false'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image for testing
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          just build ${{ inputs.path }}

      - name: Test container image
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          just test ${{ inputs.path }}

      - name: Tag and push container image to GHCR
        if: (steps.check_tag.outputs.exists == 'false') && success()
        run: |
          just publish ${{ env.REPO_URL }} ${{ inputs.path }}
