name: Trigger Read the Docs Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  trigger-rtd-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Read the Docs Build
        run: |
          curl --verbose -X POST \
               -H "Content-Type: application/json" \
               -d "{\"token\": ${{ secrets.RTD_WEBHOOK_TOKEN }}, \"branches\": [\"latest\"]}" \
               "${{ secrets.RTD_WEBHOOK_URL }}"
