name: Trigger Read the Docs Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Read the Docs Build
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               --fail \
               -d '{"token": "${{ secrets.RTD_WEBHOOK_TOKEN }}", "branches": ["${{ github.ref_name }}"]}' \
               "${{ secrets.RTD_WEBHOOK_URL }}"
