name: Trigger Read the Docs Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  trigger-rtd-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Read the Docs Build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.RTD_WEBHOOK_URL }}
          body: '{"token": "${{ secrets.RTD_WEBHOOK_TOKEN }}", "default_branch": "main", "branches": "main"}'
          github_event_payload: false
