
name: Test Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Dispatcher"]
    branches: [main]
    types:
      - completed
    paths:
      - 'containers/**'
      - 'docs/**'

jobs:
  test-docs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
        shell: bash

      - name: Set up just
        uses: extractions/setup-just@v2

      - name: Set container environment
        run: echo "CONTAINER_ENV=docker" >> $GITHUB_ENV
        shell: bash

      - name: Run doc tests
        run: uv run ./utils/test_code_blocks.py
        shell: bash

      - name: Upload results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test_results.md
          path: docs/test_results.md

