
name: Test Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Dispatcher"]
    branches: [main]
    types:
      - completed
    paths:
      - 'containers/**'
      - 'docs/**'

jobs:
  test-docs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # NOTE: `--privileged` currently doesn't work on Mac OS GHW image due to M1/Colima restrictions
        # os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
        shell: bash

      - name: Set up just
        uses: extractions/setup-just@v2

      - name: Set container environment
        run: echo "CONTAINER_ENV=docker" >> $GITHUB_ENV
        shell: bash

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run doc tests
        run: uv run ./utils/test_code_blocks.py
        shell: bash

      - name: Upload results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test_results-${{ matrix.os }}.md
          path: ${{ github.workspace }}/docs/test_results.md

