name: Test Documentation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Dispatcher"]
    branches: [main]
    types:
      - completed
    paths:
      - 'containers/**'
      - 'docs/**'

jobs:
  test-docs:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # NOTE: Mac OS and Windows tests are not included here because:
        #     - Mac OS: `--privileged` currently doesn't work due to M1/Colima restrictions
        #     - Windows: The `windows-latest` images doesn't allow testing linux based containers
        # In theory: this is less than ideal but should be fine since once we get inside the
        #     container our environments should be predictably the same
        # os: [ubuntu-latest, macos-latest, windows-latest]
        container_runtime: [docker, podman]

    name: Test Docs (${{ matrix.os }} | ${{ matrix.container_runtime }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
        shell: bash

      - name: Set up just
        uses: extractions/setup-just@v2

      - name: Set container environment
        run: echo "CONTAINER_ENV=${{ matrix.container_runtime }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up Docker
        if: matrix.container_runtime == 'docker'
        uses: docker/setup-qemu-action@v3

      - name: Set up Podman
        if: matrix.container_runtime == 'podman'
        uses: gacts/install-podman@v1

      - name: Log in to GHCR (Docker)
        if: matrix.container_runtime == 'docker'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GHCR (Podman)
        if: matrix.container_runtime == 'podman'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run doc tests
        run: uv run ./utils/test_code_blocks.py
        shell: bash

      - name: Upload results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test_results-${{ matrix.os }}-${{ matrix.container_runtime }}.md
          path: ${{ github.workspace }}/docs/test_results.md
